add_newline = false
format = """
[╭](fg:separator)\
$sudo\
$status\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
${custom.react}\
$conda\
$python\
$java\
$lua\
$c\
$dotnet\
$cmd_duration\
$time\
$line_break\
$character\
"""


###############################################################
# Pallette
#########################################################################
palette = "default"
[palettes.default]
prompt_ok  = "#63677d"
prompt_err = "#db5661"
background = "#44475A"
icon       = "#1c232d"
icon_white = "#F5F5F5"
# separator  = "#E9EAFB"
separator  = "#44475A"

sudo       = "#FFFF00"
status     = "#e23140"
hostname   = "#FFD43B"
directory  = "#E9EAFB"
duration   = "#e26f31"
git_branch = "#31e268"
git_status = "#31e268"

node_js = "#12952E"
dotnet = "#BD93F9"
python = "#4B8BBE"
conda = "#0cbd45"
java = "#ED8B00"
clang = '#00599C'
lua = "#152885"
react = "#0188c7"


###############################################################
# User & Machine
#########################################################################
[character]
format = "[╰$symbol](fg:separator) "
success_symbol = "[](fg:prompt_ok)"
error_symbol = "[](fg:prompt_err)"

[sudo]
format = "[─](fg:separator)[](fg:sudo)[$symbol](fg:icon bg:sudo)[](fg:sudo)"
symbol = ""
disabled = false

[status]
format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $status](bg:background)[](fg:background)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $pipestatus](bg:background)[](fg:background)"
disabled = false

[hostname]
format = "[─](fg:separator)[](fg:hostname)[](fg:icon_white bg:hostname)[](fg:hostname bg:background)[ $hostname](bg:background)[](fg:background)"

[directory]
format = "[─](fg:separator)[](fg:directory)[󰀵](fg:icon bg:directory)[](fg:directory bg:background)[ $read_only$truncation_symbol$path](bg:background)[](fg:background)"
truncate_to_repo = false
# truncation_length = 0
truncation_symbol = "󰉕 "
read_only = "󱃬 "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"~/LC/2_Areas/Academics" = "󰑴 "
"~/LC/2_Areas/Programming_Projects" = "󰲋 "

# Alpine = ''
# Amazon = ''
# Android = ''
# Arch = ''
# CentOS = ''
# Debian = ''
# EndeavourOS = ''
# Fedora = ''
# FreeBSD = ''
# Garuda = ''
# Gentoo = ''
# Linux = ''
# Macos = ''
# Manjaro = ''
# Mariner = ''
# Mint = ''
# NetBSD = ''
# NixOS = ''
# OpenBSD = ''
# OpenCloudOS = ''
# openEuler = ''
# openSUSE = ''
# OracleLinux = '⊂⊃'
# Pop = ''
# Raspbian = ''
# Redhat = ''
# RedHatEnterprise = ''
# Solus = ''
# SUSE = ''
# Ubuntu = ''
# Unknown = ''
# Windows = ''


###############################################################
# Technologies 
#########################################################################
[git_branch]
format = "[─](fg:separator)[](fg:git_branch)[$symbol](fg:icon bg:git_branch)[](fg:git_branch bg:background)[ $branch](bg:background)"
symbol = ""

[git_status]
format = "[](fg:background bg:git_status)[$all_status$ahead_behind](fg:icon bg:git_status)[](fg:git_status)"

[nodejs]
format = '[─](fg:separator)[](fg:node_js)[$symbol](fg:icon_white bg:node_js)[](fg:node_js bg:background)[ $version](bg:background)[](fg:background)'
symbol = "󰎙"
version_format = "${major}.${minor}"

[custom.react]
command = "grep '\"react\":' package.json | sed -E 's/.*\"react\": \"(\\^|~|>=)?([0-9]+\\.[0-9]+)(\\.[0-9]+)?\"[,]?.*$/\\2/' 2>/dev/null"
format = '[─](fg:separator)[](fg:react)[$symbol](fg:icon_white bg:react)[](fg:react bg:background)[ $output](bg:background)[](fg:background)'
symbol = ""
detect_files = [ "package.json" ]
detect_extensions = ["jsx", "tsx"]
when = "vite"
disabled = false

[python]
format = '[─](fg:separator)[](fg:python)[$symbol](fg:icon bg:python)[](fg:python bg:background)[ $version](bg:background)[](fg:background)'
symbol = ""
version_format = "${major}.${minor}"

[conda]
format = '[─](fg:separator)[](fg:conda)[$symbol](fg:icon bg:conda)[](fg:conda bg:background)[ $environment](bg:background)[](fg:background)'
symbol = "🅒"

[java]
format = '[─](fg:separator)[](fg:java)[$symbol](fg:icon_white bg:java)[](fg:java bg:background)[ $version](bg:background)[](fg:background)'
symbol = ""
version_format = "${major}.${minor}"

[c]
format = '[─](fg:separator)[](fg:clang)[$symbol](fg:icon_white bg:clang)[](fg:clang bg:background)[ $version](bg:background)[](fg:background)'
symbol = ""
version_format = "${major}.${minor}"

[lua]
format = '[─](fg:separator)[](fg:lua)[$symbol](fg:icon_white bg:lua)[](fg:lua bg:background)[ $version](bg:background)[](fg:background)'
symbol = ""
version_format = "${major}.${minor}"

[dotnet]
format = '[─](fg:separator)[](fg:dotnet)[$symbol](fg:icon bg:dotnet)[](fg:dotnet bg:background)[ $version](bg:background)[](fg:background)'
symbol = ""
version_format = "${major}.${minor}"


###############################################################
# Terminal 
#########################################################################
[fill]
symbol = '─'
style = 'fg:separator'
disabled = true

[cmd_duration]
format = "[─](fg:separator)[](fg:duration)[󱐋](fg:icon bg:duration)[](fg:duration bg:background)[ $duration](bg:background)[](fg:background)"
min_time = 1500 # milliseconds

[time]
format = "[─](fg:separator)[](fg:duration)[󰥔](fg:icon bg:duration)[](fg:duration bg:background)[ $time](bg:background)[](fg:background)"
time_format = '%H:%M'
disabled = true
